# Generated by Django 4.2.1 on 2023-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, verbose_name='文件唯一id')),
                ('file_date', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件路径')),
                ('file_path', models.CharField(max_length=1000, verbose_name='文件路径')),
                ('file_content_type', models.CharField(max_length=200, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('file_ywfl', models.CharField(max_length=200, verbose_name='文件分类')),
                ('file_ywdl', models.CharField(max_length=200, verbose_name='文件大类')),
                ('file_state', models.IntegerField(default=0, verbose_name='文件状态，0-正常；1-已失效')),
            ],
        ),
    ]
